# Generated by Django 5.0.6 on 2024-05-22 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_promotion_product_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
