# Generated by Django 5.0.6 on 2024-05-27 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
